### ISSUE TITLE
'Theme' object has no attribute 'name'

### ISSUE THREAD

**Issue by yangfangs** [hfagerlund/mkdocs-docskimmer#13]
Hi~

This theme very nice.
I use this theme step by step but when I use "mkdocs serve" can't work.

error:
```
$ mkdocs serve
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/__main__.py", line 134, in serve_command
    livereload=livereload
  File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 119, in serve
    config = builder()
  File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/serve.py", line 107, in builder
    site_dir=site_dir
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/base.py", line 115, in validate
    post_failed, post_warnings = self._post_validate()
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/base.py", line 95, in _post_validate
    config_option.post_validation(self, key_name=key)
  File "/usr/local/lib/python3.6/site-packages/mkdocs/config/config_options.py", line 430, in post_validation
    format(path=theme_config['custom_dir'], name=self.name))
AttributeError: 'Theme' object has no attribute 'name'
```

My mkdocsy.yml is:

```
site_name: test

nav:
### add your custom pages hierarchy here
- Home: index.md

theme:
  name: mkdocs
  custom_dir: 'mkdocs_docskimmer'
  include_search_page: false
  search_index_only: false
  static_templates:
  - 404.html

plugins: ['search']

# add theme version number here
extra:
  version: 0.4.0
```
I want to know how to fix it? can you help me?

**Comment by hfagerlund** [comment]
@yangfangs -
Thanks for taking the time to try out the theme, and for providing feedback.

Have you tried making the following change to `mkdocs.yml`?

```
theme:
  name: null
```
(Otherwise, it looks fine.)

`docSkimmer` is a standalone theme - it does [not override](https://www.mkdocs.org/user-guide/styling-your-docs/#using-the-theme-custom_dir) either of the built-in themes (at the time of writing, there are two 'installed themes': `mkdocs` and `readthedocs` ), therefore the theme `name` setting in `mkdocs.yml` should be `null`.

Please let me know if that solves the issue.

**Comment by yangfangs** [comment]
Thanks for your help!
I changed name "mkdocs" to "null", it’s work fine.

**Comment by hfagerlund** [comment]
Glad to hear it @yangfangs - happy that it's working for you.

**Comment by WritingSolutions2020** [comment]
For Python 3.5, `mkdocs --version` == `1.0.4`, `mkdocs-docskimmer` directory at the same level as the project's `docs` folder. Along the way I stopped then restartated the `mkdocs serve &` process.

I'm having the problem described above even though my MkDocs project's `mkdocs.yml` file includes `name: null`.

------
### The complete trace
```
[I 190124 15:36:10 watcher:92] Running task: <function serve.<locals>.builder at 0xb70d05cc> (delay: None)
INFO    -  Building documentation...
[E 190124 15:36:10 ioloop:801] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 1229, in _run
        return self.callback()
      File "/usr/local/lib/python3.5/dist-packages/livereload/handlers.py", line 66, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "/usr/local/lib/python3.5/dist-packages/livereload/watcher.py", line 93, in examine
        func()
      File "/usr/local/lib/python3.5/dist-packages/mkdocs/commands/serve.py", line 107, in builder
        site_dir=site_dir
      File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 197, in load_config
        errors, warnings = cfg.validate()
      File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 115, in validate
        post_failed, post_warnings = self._post_validate()
      File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/base.py", line 95, in _post_validate
        config_option.post_validation(self, key_name=key)
      File "/usr/local/lib/python3.5/dist-packages/mkdocs/config/config_options.py", line 430, in post_validation
        format(path=theme_config['custom_dir'], name=self.name))
    AttributeError: 'Theme' object has no attribute 'name'
```
------

------
### The _mkdocs.yml_ file:

```
site_name: MkDocs Demo

nav:
  - Intro: index.md
  - Setup: setup.md
  - Style: style.md
  - Run / Build: build.md
  - Links: links.md

theme:
  name: null
  custom_dir: 'mkdocs_docskimmer'
  include_search_page: true
  search_index_only: false
  static_templates:
  - 404.html

plugins: ["search"]

# add theme version number here
extra:
  version: 0.4.0
```
------

+ IF I cut the `theme`, `plugins`, and `extra` sections out of the `mkdocs.yml` file, THEN it builds without error.

+ IF I paste those sections back into the file, THEN as shown above, the last line of the build process ==   `AttributeError: 'Theme' object has no attribute 'name'`
